// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwbrDFT7daJc8HbctjjsTxUn65Ue2I0qo',
    appId: '1:455768986131:web:c5bc13f769df6cb59de5e6',
    messagingSenderId: '455768986131',
    projectId: 'renthub-ee6ee',
    authDomain: 'renthub-ee6ee.firebaseapp.com',
    storageBucket: 'renthub-ee6ee.appspot.com',
    measurementId: 'G-X1H095DQLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mGpxy1KpYAasKM2yxJnN1cvSqiK6zgU',
    appId: '1:455768986131:android:2708712bf7b64de79de5e6',
    messagingSenderId: '455768986131',
    projectId: 'renthub-ee6ee',
    storageBucket: 'renthub-ee6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvk7upC78QcwJw8GeYk9xV6XP7Oq34KKo',
    appId: '1:455768986131:ios:a4edb5f4d18940b69de5e6',
    messagingSenderId: '455768986131',
    projectId: 'renthub-ee6ee',
    storageBucket: 'renthub-ee6ee.appspot.com',
    iosBundleId: 'com.example.rentHubFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvk7upC78QcwJw8GeYk9xV6XP7Oq34KKo',
    appId: '1:455768986131:ios:942c44cc3229a2b09de5e6',
    messagingSenderId: '455768986131',
    projectId: 'renthub-ee6ee',
    storageBucket: 'renthub-ee6ee.appspot.com',
    iosBundleId: 'com.example.rentHubFlutterProject.RunnerTests',
  );
}
